### ISSUE TITLE
No funciona el sistema de actualización automática del launcher

### ISSUE THREAD

**Issue by Crujera27** [VI-Software/vis-launcher#1]
El sistema de actualizaciones automáticas del launcher siempre detecta la versión instalada como la más nueva y estable.

**Comment by Crujera27** [comment]
Está siendo investigado

**Comment by Crujera27** [comment]
Tras una investigación, he podido apreciar que parece un error de Electron con algunas versiones en concreto de Windows. Seguimos investigando en como solucionar este problema.

**Comment by zaibiti** [comment]
Debería estar arreglado en Ubuntu/Debian por el commit #8c81537

**Comment by Crujera27** [comment]
Solucionado en la relase 1.5.2
